#!/bin/bash
#
# Environment Variables:
#   MERRA2_DATA_PATH      Location merra2 output hdf data from merra24clavrx.py.
#   
# Month and Year must be entered together.
#   YEAR                  Year to check
#   MONTH                 Month to check
#
#function usage {
#cat << EndOfMessage
#
#    Usage: sh $0 [options] YYYY MM"
#
#    Count files for month in merra2 data directory to make
#    sure 4 output files per day have been created for each 
#    day of month under inspection.
#
#    Options:
#    	-w merra2 data directory 
#          default:
#        $DATA_PATH
#   	-h Display this usage information
#
#EndOfMessage
#    $VAR
#    exit
#}


DATA_PATH=/apollo/cloud/Ancil_Data/clavrx_ancil_data/dynamic/merra2

if [ $# -eq 0 ]; then
	`/bin/pod2usage $0`
	exit
fi

while getopts "w:h" flag; do
	case "$flag" in
		w) DATA_PATH=$OPTARG;;
		h) `/bin/pod2usage $0`
	            exit;;
	esac
done

YEAR=${@:$OPTIND:1}
MONTH=${@:$OPTIND+1:1}

if [ -z $YEAR ] || [ -z $MONTH ];then
        `/bin/pod2usage $0`
         exit
fi

month=`printf "%02d" $MONTH`

str_month=`date -d ${YEAR}-${month}-01 +"%B %Y"`

DATA_PATH=${DATA_PATH}/${YEAR}

ndays=`cal ${MONTH} ${YEAR} | awk 'NF {DAYS = $NF}; END {print DAYS}'`
ntotal=$(( $ndays*4 ))

nfiles=`find ${DATA_PATH} -name "merra.${YEAR:2:2}${month}*.hdf" | wc -l`

echo "===="
if [ ${nfiles} -lt ${ntotal} ]; then
	echo "ERROR: Only ${nfiles} files in ${DATA_PATH}. ${ntotal} are expected for $str_month"
	echo "===="
	exit $ndays 
elif [ ${nfiles} -gt ${ntotal} ]; then
	echo "ERROR: $DATA_PATH has (${nfiles}) files. ${ntotal} expected for $str_month"
	echo "===="
        exit $ndays 
else
	echo "COMPLETE: There are a complete set of files for $str_month: ${nfiles}"
	echo "===="
fi

: <<=cut
=pod

=head1 NAME


    count_inventory.sh - Count MERRA2 output files generated by month in data directory

=head1 SYNOPSIS

    sh count_inventory.sh [options] YYYY MM"
   
      where: YYYY is the year (4 digit required)
             MM   is the 1 or 2-digit month

   Recognized optional command line arguments
      -w <string>  -- Use an alternate merra2 data path
       (default: /apollo/cloud/Ancil_Data/clavrx_ancil_data/dynamic/merra2)
      -h  -- Display usage message


=head1 DESCRIPTION

    Count files by given Year/month in merra2 data directory.
    Compare against expected count (4/day).

=head2 Requirements

4 digit year is necessary otherwise usage will be shown.

=cut

exit

